[package]
name = "streamduck-core"
authors = ["TheJebForge"]
version = "0.2.0"
description = "Core library of the Streamduck project"
edition = "2021"
readme = "../Readme.md"
license-file = "../LICENSE"
repository = "https://github.com/streamduck-org/streamduck"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
streamdeck = "0.6"
hidapi = "1.4.1"
image = "0.24.1"
rand = "0.8.4"
rusttype = "0.9.2"
base64 = "0.13.0"
palette = "0.6.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"
log = "0.4"
flate2 = "1.0"
toml = "0.5.8"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
strum = "0.23"
strum_macros = "0.23"
itertools = "0.10.3"
dirs = "4.0.0"
async-trait = "0.1.56"
async-recursion = "1.0.0"
tokio = { version = "1", features = ["full"] }
rayon = "1.5.3"
futures = "0.3.21"
