[package]
name = "streamduck-daemon"
authors = ["TheJebForge"]
version = "0.0.12"
description = "Daemon of the Streamduck project"
edition = "2021"
readme = "../Readme.md"
license-file = "../LICENSE"
repository = "https://github.com/streamduck-org/streamduck"

[lib]
name = "streamduck_daemon"
path = "src/lib.rs"

[[bin]]
name = "streamduck_daemon"
path = "src/main.rs"

[dependencies]
streamduck-core = {path = "../streamduck-core", version = "0.0.12"}
streamduck-actions = {path = "../streamduck-actions", version = "0.0.12"}
base64 = "0.13.0"
flate2 = "1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"
flexi_logger = "0.22.2"
log = "0.4"
ctrlc = "3.2.1"
strum = "0.23"
strum_macros = "0.23"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.4.1"