[package]
name = "streamduck-daemon"
authors = ["TheJebForge"]
version = "0.2.0"
description = "Daemon of the Streamduck project"
edition = "2021"
readme = "../Readme.md"
license = "LGPL-2.1-only"
repository = "https://github.com/streamduck-org/streamduck"

[lib]
name = "streamduck_daemon"
path = "src/lib.rs"

[[bin]]
name = "streamduck_daemon"
path = "src/main.rs"

[dependencies]
streamduck-core = {path = "../streamduck-core", version = "0.2.0" }
streamduck-actions = {path = "../streamduck-actions", version = "0.2.0" }
base64 = "0.13.0"
flate2 = "1.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
flexi_logger = "0.22.5"
log = "0.4"

ctrlc = { version = "3.2.2", features = ["termination"]}
clap = {version = "4.0.15", features = ["cargo"]}
strum = "0.24"
strum_macros = "0.24"
itertools = "0.10.3"

tokio = { version = "1", features = ["full"] }
rayon = "1.5.3"
num_cpus = "1.13.1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["wincon"]}

[package.metadata.wix]
name = "Streamduck"
